# Configuration Nixpacks pour Railway
# Nixpacks est le builder par d√©faut de Railway

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "pnpm install",
  "npx playwright install chromium --with-deps"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"
